### ISSUE TITLE
can't save image files

### ISSUE THREAD

**Issue by mrtillman** [mrtillman/grav.client#37]
The `saveImage` and `saveEncodedImage` methods are no longer working:

## repro:

```js
// saving an image file
const { GravatarClient } = require("grav.client");
const { join } = require("path");
const { readFileSync } = require("fs");

const client = new GravatarClient("username", "password");

const imgPath = join(__dirname, "../Common/Assets/bubba.jpg");

client.saveImage(imgPath).then(console.log).catch(console.log);

// saving an encoded image
const bitmap = readFileSync(imgPath);
const imageData = Buffer.from(bitmap).toString("base64");
client.saveEncodedImage(imageData, "jpeg").then(console.log).catch(console.log);
```

## result:

```sh
FaultError: [-100]: Could not fetch file
    at new MethodResponse (/home/user/Projects/grav.client/Release/Domain/method-responses.js:23:19)
    at new SaveImageUrlMethodResponse (/home/stephen/Projects/grav.client/Release/Domain/method-responses.js:101:9)
    at GravatarClient.<anonymous> (/home/stephen/Projects/grav.client/Release/Services/gravatar.service.js:103:40)
    at Generator.next (<anonymous>)
    at fulfilled (/home/stephen/Projects/grav.client/Release/Services/gravatar.service.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  faultCode: -100,
  faultString: 'Could not fetch file'
}
```

**Comment by mrtillman** [comment]
resolved
